server:
  port: 8190
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - email
              - profile
              - openid
          github:
            clientId: 
            clientSecret: 
            scope:
              - user
          facebook:
            clientId: 
            clientSecret: 
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
