server:
  port: 8190
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-251-245-108.eu-west-1.compute.amazonaws.com:5432/d7rcs7ltcal5nt
    username: cmxkeawrphunrr
    password: 48f72c2a13dfed601fced5e99e7d400aca0c6f3f8007b11efe656fd2f85e5be5
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 23053377844-eulbn7b8ovsr31lgvo72135nsl0s950b.apps.googleusercontent.com
            client-secret: zII7NlMtv5ru9zeuIz9sewDz
            scope:
              - email
              - profile
              - openid
          github:
            clientId: 05adffca120cfc8ffba4
            clientSecret: 4546e1ae6d4f1128d07959fed6711b7437bd31c0
            scope:
              - user
          facebook:
            clientId: 238999834836830
            clientSecret: 9a3ae93036bc4ceef119aed2d6f03972
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect